apiVersion: v1
kind: Service
metadata:
  name: spec-and-ship
  namespace: default
spec:
  selector:
    app: spec-and-ship
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7007
      name: http
  type: LoadBalancer
